[build]
  # Build command - this will create the production bundle
  command = "npm run vite:build:prod"
  
  # Directory to publish (where the built files are)
  publish = "dist"
  
  # Functions directory (if you have any)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "22.12"

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching and security
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"